export { createChannel, type CreateChannelOpts, type ChannelHandle } from "./channel/create.js";
export { loginQR, type LoginQROpts } from "./channel/login-flow.js";
export type { ChannelMsg, MediaRef, Reply, ReplyTextOpts } from "./channel/types.js";
export type { QRLoginHandle, LoginResult, QrTerminalOpts, QrPngOpts, QrSvgOpts, WaitForLoginOpts } from "./channel/types.js";
export type { Store } from "./store/types.js";
export { JsonFileStore } from "./store/file.js";
export { MemoryStore } from "./store/memory.js";
export { ChannelError, WechatApiError, MediaError } from "./errors.js";
export type { ChannelErrorCode, WechatApiErrorPayload, MediaPhase } from "./errors.js";
export { WechatApiClient, type ApiClientOptions } from "./wechat/api.js";
export type { WeixinMessage, MessageItem } from "./wechat/types.js";
